fixtures:
  repositories:
  forge_modules:
    account:
      repo: "torrancew/account"
      ref: "0.0.5"
    beaver:
      repo: "evenup/beaver"
      ref: "1.1.0"
    concat:
      repo: "puppetlabs/concat"
      ref: "1.2.0"
    stdlib:
      repo: "puppetlabs/stdlib"
      ref: "3.2.0"
  symlinks:
    common: "#{source_dir}"
